# Generated by Django 5.0.1 on 2024-05-09 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('usuario_encargado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Impresora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_conexion', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('localizacion', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=50)),
                ('modelo_fabricacion', models.CharField(max_length=50)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_impresoras.local')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoSubido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='uploads/documentos/')),
                ('tipo', models.CharField(max_length=100)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('color', models.BooleanField(default=False)),
                ('doscaras', models.BooleanField(default=False)),
                ('numero_copias', models.IntegerField(default=1)),
                ('numero_paginas', models.IntegerField(default=1)),
                ('estado', models.CharField(choices=[('p', 'Pendiente'), ('i', 'Impreso')], default='p', max_length=2)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_subidos', to=settings.AUTH_USER_MODEL)),
                ('impresora', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_impresoras.impresora')),
                ('local', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_impresoras.local')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('impresora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_impresoras.impresora')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
