# Generated by Django 5.0 on 2023-12-06 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_impresoras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='usuario_encargado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='impresora',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_impresoras.local'),
        ),
        migrations.AddField(
            model_name='registroactividad',
            name='impresora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_impresoras.impresora'),
        ),
        migrations.AddField(
            model_name='registroactividad',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
